CREATE TABLE IF NOT EXISTS `la_aigc_canvas_project` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` int unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `name` varchar(120) NOT NULL DEFAULT '未命名项目' COMMENT '项目名称',
  `thumbnail` varchar(500) NOT NULL DEFAULT '' COMMENT '缩略图',
  `nodes_json` longtext COMMENT '节点JSON',
  `edges_json` longtext COMMENT '边JSON',
  `viewport_json` text COMMENT '视口JSON',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态',
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_user` (`tenant_id`,`user_id`,`delete_time`),
  KEY `idx_tenant_update` (`tenant_id`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='无限画布项目';

CREATE TABLE IF NOT EXISTS `la_aigc_canvas_run` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` int unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `project_id` int unsigned NOT NULL DEFAULT 0 COMMENT '画布项目ID',
  `node_id` varchar(120) NOT NULL DEFAULT '' COMMENT '节点ID',
  `run_type` varchar(30) NOT NULL DEFAULT '' COMMENT 'image/video/text/workflow',
  `source_app_code` varchar(64) NOT NULL DEFAULT '' COMMENT '调用应用',
  `source_task_id` int unsigned NOT NULL DEFAULT 0 COMMENT '关联任务ID',
  `status` varchar(30) NOT NULL DEFAULT 'running' COMMENT 'running/success/failed',
  `prompt` text COMMENT '提示词',
  `params_json` longtext COMMENT '调用参数',
  `result_json` longtext COMMENT '执行结果',
  `error` text COMMENT '错误信息',
  `duration_ms` int unsigned NOT NULL DEFAULT 0 COMMENT '耗时',
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `finish_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_project` (`tenant_id`,`project_id`,`delete_time`),
  KEY `idx_tenant_user` (`tenant_id`,`user_id`,`delete_time`),
  KEY `idx_source_task` (`source_app_code`,`source_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='无限画布运行记录';

CREATE TABLE IF NOT EXISTS `la_aigc_canvas_skill` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0 COMMENT 'Tenant ID',
  `user_id` int unsigned NOT NULL DEFAULT 0 COMMENT 'Creator admin/user ID',
  `skill_key` varchar(120) NOT NULL DEFAULT '' COMMENT 'Skill key',
  `name` varchar(120) NOT NULL DEFAULT '' COMMENT 'Skill name',
  `description` varchar(500) NOT NULL DEFAULT '' COMMENT 'Skill description',
  `category` varchar(80) NOT NULL DEFAULT 'general' COMMENT 'Skill category',
  `skill_type` varchar(40) NOT NULL DEFAULT 'agent_prompt' COMMENT 'agent_prompt/workflow_template',
  `source_type` varchar(40) NOT NULL DEFAULT 'tenant' COMMENT 'builtin/tenant',
  `content_markdown` longtext COMMENT 'Agent prompt markdown',
  `trigger_description` text COMMENT 'Trigger description',
  `workflow_json` longtext COMMENT 'Workflow template JSON',
  `examples_json` text COMMENT 'Positive examples JSON',
  `negative_examples_json` text COMMENT 'Negative examples JSON',
  `required_slots_json` text COMMENT 'Required slots JSON',
  `optional_slots_json` text COMMENT 'Optional slots JSON',
  `defaults_json` text COMMENT 'Default slot values JSON',
  `clarification_policy_json` text COMMENT 'Clarification policy JSON',
  `tool_policy_json` text COMMENT 'Tool policy JSON',
  `output_policy_json` text COMMENT 'Output policy JSON',
  `agent_policy_json` text COMMENT 'Agent orchestration policy JSON',
  `tool_schema_json` text COMMENT 'Allowed tool schema JSON',
  `canvas_output_policy_json` text COMMENT 'JSON Canvas output policy',
  `cover_url` varchar(500) NOT NULL DEFAULT '' COMMENT 'Cover URL',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT 'Status',
  `version` int unsigned NOT NULL DEFAULT 1 COMMENT 'Skill version',
  `sort` int NOT NULL DEFAULT 0 COMMENT 'Sort',
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_skill_key` (`tenant_id`,`skill_key`,`delete_time`),
  KEY `idx_tenant_type_status` (`tenant_id`,`skill_type`,`status`,`delete_time`),
  KEY `idx_tenant_sort` (`tenant_id`,`sort`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC canvas skills';

CREATE TABLE IF NOT EXISTS `la_aigc_canvas_agent_batch` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `user_id` int unsigned NOT NULL DEFAULT 0,
  `project_id` int unsigned NOT NULL DEFAULT 0,
  `thread_id` int unsigned NOT NULL DEFAULT 0,
  `run_id` int unsigned NOT NULL DEFAULT 0,
  `analysis_message_id` int unsigned NOT NULL DEFAULT 0,
  `request_id` varchar(96) NOT NULL DEFAULT '',
  `skill_key` varchar(120) NOT NULL DEFAULT '',
  `status` varchar(40) NOT NULL DEFAULT 'awaiting_initial_confirmation',
  `execution_mode` varchar(30) NOT NULL DEFAULT 'batch',
  `batch_kind` varchar(24) NOT NULL DEFAULT 'initial',
  `parent_batch_id` int unsigned NOT NULL DEFAULT 0,
  `revision_no` int unsigned NOT NULL DEFAULT 0,
  `revision_instruction` text,
  `decision_json` longtext,
  `scope_json` longtext,
  `total_count` int unsigned NOT NULL DEFAULT 0,
  `next_offset` int unsigned NOT NULL DEFAULT 0,
  `batch_size` int unsigned NOT NULL DEFAULT 5,
  `current_wave` int unsigned NOT NULL DEFAULT 0,
  `notified_wave` int unsigned NOT NULL DEFAULT 0,
  `analysis_json` longtext,
  `sections_json` longtext,
  `references_json` longtext,
  `media_config_json` longtext,
  `tasks_json` longtext,
  `error` text,
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_request` (`tenant_id`,`user_id`,`request_id`,`delete_time`),
  KEY `idx_batch_thread` (`tenant_id`,`thread_id`,`status`,`delete_time`),
  KEY `idx_batch_project` (`tenant_id`,`project_id`,`delete_time`),
  KEY `idx_batch_parent` (`tenant_id`,`parent_batch_id`,`revision_no`,`delete_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC canvas agent media batches';
