CREATE TABLE IF NOT EXISTS `la_aigc_canvas_agent_batch` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `user_id` int unsigned NOT NULL DEFAULT 0,
  `project_id` int unsigned NOT NULL DEFAULT 0,
  `thread_id` int unsigned NOT NULL DEFAULT 0,
  `run_id` int unsigned NOT NULL DEFAULT 0,
  `analysis_message_id` int unsigned NOT NULL DEFAULT 0,
  `request_id` varchar(96) NOT NULL DEFAULT '',
  `skill_key` varchar(120) NOT NULL DEFAULT '',
  `status` varchar(40) NOT NULL DEFAULT 'awaiting_initial_confirmation',
  `execution_mode` varchar(30) NOT NULL DEFAULT 'batch',
  `total_count` int unsigned NOT NULL DEFAULT 0,
  `next_offset` int unsigned NOT NULL DEFAULT 0,
  `batch_size` int unsigned NOT NULL DEFAULT 5,
  `current_wave` int unsigned NOT NULL DEFAULT 0,
  `notified_wave` int unsigned NOT NULL DEFAULT 0,
  `analysis_json` longtext,
  `sections_json` longtext,
  `references_json` longtext,
  `media_config_json` longtext,
  `tasks_json` longtext,
  `error` text,
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_request` (`tenant_id`,`user_id`,`request_id`,`delete_time`),
  KEY `idx_batch_thread` (`tenant_id`,`thread_id`,`status`,`delete_time`),
  KEY `idx_batch_project` (`tenant_id`,`project_id`,`delete_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC canvas agent media batches';
