CREATE TABLE IF NOT EXISTS `la_aigc_canvas_skill` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0 COMMENT 'Tenant ID',
  `user_id` int unsigned NOT NULL DEFAULT 0 COMMENT 'Creator admin/user ID',
  `skill_key` varchar(120) NOT NULL DEFAULT '' COMMENT 'Skill key',
  `name` varchar(120) NOT NULL DEFAULT '' COMMENT 'Skill name',
  `description` varchar(500) NOT NULL DEFAULT '' COMMENT 'Skill description',
  `category` varchar(80) NOT NULL DEFAULT 'general' COMMENT 'Skill category',
  `skill_type` varchar(40) NOT NULL DEFAULT 'agent_prompt' COMMENT 'agent_prompt/workflow_template',
  `source_type` varchar(40) NOT NULL DEFAULT 'tenant' COMMENT 'builtin/tenant',
  `content_markdown` longtext COMMENT 'Agent prompt markdown',
  `trigger_description` text COMMENT 'Trigger description',
  `workflow_json` longtext COMMENT 'Workflow template JSON',
  `examples_json` text COMMENT 'Positive examples JSON',
  `negative_examples_json` text COMMENT 'Negative examples JSON',
  `required_slots_json` text COMMENT 'Required slots JSON',
  `optional_slots_json` text COMMENT 'Optional slots JSON',
  `defaults_json` text COMMENT 'Default slot values JSON',
  `clarification_policy_json` text COMMENT 'Clarification policy JSON',
  `tool_policy_json` text COMMENT 'Tool policy JSON',
  `output_policy_json` text COMMENT 'Output policy JSON',
  `cover_url` varchar(500) NOT NULL DEFAULT '' COMMENT 'Cover URL',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT 'Status',
  `version` int unsigned NOT NULL DEFAULT 1 COMMENT 'Skill version',
  `sort` int NOT NULL DEFAULT 0 COMMENT 'Sort',
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_skill_key` (`tenant_id`,`skill_key`,`delete_time`),
  KEY `idx_tenant_type_status` (`tenant_id`,`skill_type`,`status`,`delete_time`),
  KEY `idx_tenant_sort` (`tenant_id`,`sort`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC canvas skills';
