expose_php = Off
memory_limit = 512M
max_execution_time = 600
max_input_time = 600
post_max_size = 512M
upload_max_filesize = 512M
date.timezone = Asia/Shanghai
session.save_path = "/var/www/html/runtime/sessions"

opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 192
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
