-- Durable, tenant-scoped first-frame generation for short-drama canvas videos.
CREATE TABLE IF NOT EXISTS `la_aigc_short_drama_canvas_poster_job` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `user_id` int unsigned NOT NULL DEFAULT 0,
  `canvas_id` int unsigned NOT NULL DEFAULT 0,
  `node_id` varchar(64) NOT NULL DEFAULT '',
  `video_uri` varchar(500) NOT NULL DEFAULT '',
  `storage_scope` varchar(30) NOT NULL DEFAULT '',
  `storage_engine` varchar(30) NOT NULL DEFAULT '',
  `storage_domain` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `attempts` int unsigned NOT NULL DEFAULT 0,
  `max_attempts` int unsigned NOT NULL DEFAULT 4,
  `next_run_time` int unsigned NOT NULL DEFAULT 0,
  `lease_token` varchar(120) NOT NULL DEFAULT '',
  `lease_expire_time` int unsigned NOT NULL DEFAULT 0,
  `poster_uri` varchar(500) NOT NULL DEFAULT '',
  `poster_scope` varchar(30) NOT NULL DEFAULT '',
  `poster_engine` varchar(30) NOT NULL DEFAULT '',
  `poster_domain` varchar(255) NOT NULL DEFAULT '',
  `last_error` varchar(500) NOT NULL DEFAULT '',
  `idempotency_key` char(40) NOT NULL DEFAULT '',
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `finish_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_idempotency` (`idempotency_key`),
  KEY `idx_claim` (`status`,`next_run_time`,`lease_expire_time`),
  KEY `idx_canvas` (`tenant_id`,`user_id`,`canvas_id`,`node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI短剧画布视频首帧任务';
