CREATE TABLE IF NOT EXISTS `la_aigc_canvas_agent_subtask` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `user_id` int unsigned NOT NULL DEFAULT 0,
  `project_id` int unsigned NOT NULL DEFAULT 0,
  `thread_id` int unsigned NOT NULL DEFAULT 0,
  `parent_run_id` bigint unsigned NOT NULL DEFAULT 0,
  `child_run_id` bigint unsigned NOT NULL DEFAULT 0,
  `request_id` varchar(96) NOT NULL DEFAULT '',
  `agent_code` varchar(64) NOT NULL DEFAULT '',
  `sequence` int unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'pending',
  `payload_json` longtext,
  `result_json` longtext,
  `error` text,
  `attempts` int unsigned NOT NULL DEFAULT 0,
  `max_attempts` int unsigned NOT NULL DEFAULT 2,
  `lease_token` varchar(128) NOT NULL DEFAULT '',
  `lease_expire_time` int unsigned NOT NULL DEFAULT 0,
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `finish_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_parent_status` (`parent_run_id`,`status`,`delete_time`),
  KEY `idx_claim` (`status`,`lease_expire_time`,`sequence`,`id`),
  KEY `idx_tenant_request` (`tenant_id`,`user_id`,`request_id`,`delete_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC canvas durable Agent subtasks';
