-- Stage 0 market trace fields. Each ALTER is atomic and safe to re-run on MySQL 5.7.
SET @market_trace_table_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_product_promo_video_task');
SET @market_trace_sql := (SELECT IF(@market_trace_table_exists > 0 AND COUNT(*) = 0, 'ALTER TABLE `la_aigc_product_promo_video_task` ADD COLUMN `idempotency_key` varchar(100) DEFAULT NULL, ADD COLUMN `market_request_id` varchar(120) NOT NULL DEFAULT '''', ADD COLUMN `market_retry_count` tinyint unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_error_code` varchar(80) NOT NULL DEFAULT '''', ADD KEY `idx_market_request` (`market_request_id`), ADD KEY `idx_market_idempotency` (`tenant_id`,`user_id`,`idempotency_key`)', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_product_promo_video_task' AND COLUMN_NAME = 'idempotency_key');
PREPARE market_trace_stmt FROM @market_trace_sql; EXECUTE market_trace_stmt; DEALLOCATE PREPARE market_trace_stmt;

SET @market_trace_table_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_music_task');
SET @market_trace_sql := (SELECT IF(@market_trace_table_exists > 0 AND COUNT(*) = 0, 'ALTER TABLE `la_aigc_music_task` ADD COLUMN `app_task_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `consumption_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_product_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_sku_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `pricing_snapshot` text, ADD COLUMN `market_request_id` varchar(120) NOT NULL DEFAULT '''', ADD COLUMN `market_retry_count` tinyint unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_error_code` varchar(80) NOT NULL DEFAULT '''', ADD KEY `idx_market_app_task` (`app_task_id`), ADD KEY `idx_market_consumption` (`consumption_id`), ADD KEY `idx_market_request` (`market_request_id`)', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_music_task' AND COLUMN_NAME = 'app_task_id');
PREPARE market_trace_stmt FROM @market_trace_sql; EXECUTE market_trace_stmt; DEALLOCATE PREPARE market_trace_stmt;

SET @market_trace_table_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_digital_human_task');
SET @market_trace_sql := (SELECT IF(@market_trace_table_exists > 0 AND COUNT(*) = 0, 'ALTER TABLE `la_aigc_digital_human_task` ADD COLUMN `app_task_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `consumption_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_product_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_sku_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `pricing_snapshot` text, ADD COLUMN `idempotency_key` varchar(100) DEFAULT NULL, ADD COLUMN `market_request_id` varchar(120) NOT NULL DEFAULT '''', ADD COLUMN `market_retry_count` tinyint unsigned NOT NULL DEFAULT 0, ADD COLUMN `billing_status` varchar(30) NOT NULL DEFAULT ''none'', ADD COLUMN `market_error_code` varchar(80) NOT NULL DEFAULT '''', ADD KEY `idx_market_app_task` (`app_task_id`), ADD KEY `idx_market_consumption` (`consumption_id`), ADD KEY `idx_market_request` (`market_request_id`), ADD KEY `idx_market_idempotency` (`tenant_id`,`user_id`,`idempotency_key`)', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_digital_human_task' AND COLUMN_NAME = 'app_task_id');
PREPARE market_trace_stmt FROM @market_trace_sql; EXECUTE market_trace_stmt; DEALLOCATE PREPARE market_trace_stmt;

SET @market_trace_table_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_image_human_task');
SET @market_trace_sql := (SELECT IF(@market_trace_table_exists > 0 AND COUNT(*) = 0, 'ALTER TABLE `la_image_human_task` ADD COLUMN `app_task_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `consumption_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_product_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_sku_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `pricing_snapshot` text, ADD COLUMN `idempotency_key` varchar(100) DEFAULT NULL, ADD COLUMN `market_request_id` varchar(120) NOT NULL DEFAULT '''', ADD COLUMN `market_retry_count` tinyint unsigned NOT NULL DEFAULT 0, ADD COLUMN `billing_status` varchar(30) NOT NULL DEFAULT ''none'', ADD COLUMN `market_error_code` varchar(80) NOT NULL DEFAULT '''', ADD KEY `idx_market_app_task` (`app_task_id`), ADD KEY `idx_market_consumption` (`consumption_id`), ADD KEY `idx_market_request` (`market_request_id`), ADD KEY `idx_market_idempotency` (`tenant_id`,`user_id`,`idempotency_key`)', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_image_human_task' AND COLUMN_NAME = 'app_task_id');
PREPARE market_trace_stmt FROM @market_trace_sql; EXECUTE market_trace_stmt; DEALLOCATE PREPARE market_trace_stmt;

SET @market_trace_table_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_smart_clip_task');
SET @market_trace_sql := (SELECT IF(@market_trace_table_exists > 0 AND COUNT(*) = 0, 'ALTER TABLE `la_smart_clip_task` ADD COLUMN `app_task_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `consumption_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_product_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_sku_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `pricing_snapshot` text, ADD COLUMN `idempotency_key` varchar(100) DEFAULT NULL, ADD COLUMN `market_request_id` varchar(120) NOT NULL DEFAULT '''', ADD COLUMN `market_retry_count` tinyint unsigned NOT NULL DEFAULT 0, ADD COLUMN `billing_status` varchar(30) NOT NULL DEFAULT ''none'', ADD COLUMN `market_error_code` varchar(80) NOT NULL DEFAULT '''', ADD KEY `idx_market_app_task` (`app_task_id`), ADD KEY `idx_market_consumption` (`consumption_id`), ADD KEY `idx_market_request` (`market_request_id`), ADD KEY `idx_market_idempotency` (`tenant_id`,`user_id`,`idempotency_key`)', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_smart_clip_task' AND COLUMN_NAME = 'app_task_id');
PREPARE market_trace_stmt FROM @market_trace_sql; EXECUTE market_trace_stmt; DEALLOCATE PREPARE market_trace_stmt;

SET @market_trace_table_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_action_transfer_task');
SET @market_trace_sql := (SELECT IF(@market_trace_table_exists > 0 AND COUNT(*) = 0, 'ALTER TABLE `la_aigc_action_transfer_task` ADD COLUMN `app_task_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `consumption_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_product_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_sku_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `pricing_snapshot` text, ADD COLUMN `idempotency_key` varchar(100) DEFAULT NULL, ADD COLUMN `market_request_id` varchar(120) NOT NULL DEFAULT '''', ADD COLUMN `market_retry_count` tinyint unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_error_code` varchar(80) NOT NULL DEFAULT '''', ADD KEY `idx_market_app_task` (`app_task_id`), ADD KEY `idx_market_consumption` (`consumption_id`), ADD KEY `idx_market_request` (`market_request_id`), ADD KEY `idx_market_idempotency` (`tenant_id`,`user_id`,`idempotency_key`)', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_action_transfer_task' AND COLUMN_NAME = 'app_task_id');
PREPARE market_trace_stmt FROM @market_trace_sql; EXECUTE market_trace_stmt; DEALLOCATE PREPARE market_trace_stmt;

SET @market_trace_table_exists := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_person_replacement_task');
SET @market_trace_sql := (SELECT IF(@market_trace_table_exists > 0 AND COUNT(*) = 0, 'ALTER TABLE `la_aigc_person_replacement_task` ADD COLUMN `app_task_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `consumption_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_product_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_sku_id` int unsigned NOT NULL DEFAULT 0, ADD COLUMN `pricing_snapshot` text, ADD COLUMN `idempotency_key` varchar(100) DEFAULT NULL, ADD COLUMN `market_request_id` varchar(120) NOT NULL DEFAULT '''', ADD COLUMN `market_retry_count` tinyint unsigned NOT NULL DEFAULT 0, ADD COLUMN `market_error_code` varchar(80) NOT NULL DEFAULT '''', ADD KEY `idx_market_app_task` (`app_task_id`), ADD KEY `idx_market_consumption` (`consumption_id`), ADD KEY `idx_market_request` (`market_request_id`), ADD KEY `idx_market_idempotency` (`tenant_id`,`user_id`,`idempotency_key`)', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'la_aigc_person_replacement_task' AND COLUMN_NAME = 'app_task_id');
PREPARE market_trace_stmt FROM @market_trace_sql; EXECUTE market_trace_stmt; DEALLOCATE PREPARE market_trace_stmt;
