(function () {
  'use strict';
  var paths = ['/app/aigc_geo', '/app/aigc_geo/', '/app/aigc_geo/config', '/app/aigc_geo/config/', '/app/aigc_geo/keywords', '/app/aigc_geo/keywords/', '/app/aigc_geo/articles', '/app/aigc_geo/articles/', '/app/aigc_geo/diagnosis', '/app/aigc_geo/diagnosis/', '/app/aigc_geo/tasks', '/app/aigc_geo/tasks/'];
  var id = 'aigc-geo-admin';
  var mounted = false;
  function isPage() { return paths.indexOf(window.location.pathname) !== -1; }
  function css() { if (document.querySelector('link[data-geo-admin-css]')) return; var link = document.createElement('link'); link.rel = 'stylesheet'; link.href = '/aigc-geo-admin.css?v=20260825-geo-v1'; link.dataset.geoAdminCss = '1'; document.head.appendChild(link); }
  function stored(key) { try { var raw = window.localStorage.getItem('__like_admin_saas_tenant__' + key) || window.localStorage.getItem(key) || ''; if (!raw) return ''; var value = JSON.parse(raw); return value && value.value !== undefined ? value.value : raw; } catch (_) { return ''; } }
  async function api(path, options) { var input = options || {}; var headers = Object.assign({ 'Content-Type': 'application/json' }, input.headers || {}); var token = stored('token'); var tenantId = stored('tenant_id'); if (token && !headers.token) headers.token = token; if (tenantId && !headers['tenant-id']) headers['tenant-id'] = tenantId; var init = Object.assign({ credentials: 'include', headers: headers }, input); init.headers = headers; var response = await fetch('/tenantapi/' + path, init); var payload = await response.json().catch(function () { return {}; }); if (!response.ok || (payload.code !== undefined && Number(payload.code) !== 1)) throw new Error(payload.msg || payload.message || '请求失败'); return payload.data !== undefined ? payload.data : payload; }
  function el(tag, cls, text) { var node = document.createElement(tag); if (cls) node.className = cls; if (text !== undefined) node.textContent = text; return node; }
  function render() {
    css();
    var root = el('section', '', ''); root.id = id; root.className = 'geo-admin';
    root.innerHTML = '<div class="geo-admin__shell"><header><div><span class="geo-admin__eyebrow">GEO MARKETING CONTROL</span><h1>GEO营销优化系统</h1><p>品牌资料、内容资产、AI 搜索检测和算力超市通道统一管理</p></div><span id="geo-admin-status" class="geo-admin__status">读取中</span></header><nav class="geo-admin__tabs"><button type="button" data-tab="summary" class="is-active">概览</button><button type="button" data-tab="config">品牌配置</button><button type="button" data-tab="keywords">问题关键词</button><button type="button" data-tab="articles">内容生产</button><button type="button" data-tab="diagnosis">品牌检测</button><button type="button" data-tab="tasks">任务记录</button></nav><main id="geo-admin-content"></main></div>';
    document.body.appendChild(root); mounted = true;
    var content = root.querySelector('#geo-admin-content'); var status = root.querySelector('#geo-admin-status'); var tab = 'summary'; var config = {};
    function setStatus(text, kind) { status.textContent = text; status.className = 'geo-admin__status' + (kind ? ' is-' + kind : ''); }
    function card(title, text) { var node = el('article', 'geo-admin__card'); node.appendChild(el('h2', '', title)); if (text) node.appendChild(el('p', 'geo-admin__muted', text)); return node; }
    async function loadSummary() { setStatus('读取中'); try { var data = await api('app.aigc_geo.console/summary', { method: 'GET', headers: {} }); config = data.config || {}; content.innerHTML = ''; var market = data.market || {}; var headline = card('应用状态', Number(config.status) === 1 ? '运行中，可继续使用现有 GEO 前端。' : '已停用，用户端暂不可提交任务。'); headline.appendChild(el('div', 'geo-admin__metric-grid', '')); var metrics = headline.querySelector('.geo-admin__metric-grid'); Object.keys(data.stats || {}).forEach(function (key) { var item = el('div', 'geo-admin__metric'); item.appendChild(el('strong', '', String(data.stats[key])); item.appendChild(el('span', '', key.replace(/_/g, ' '))); metrics.appendChild(item); }); content.appendChild(headline); var marketCard = card('算力超市通道', market.message || '暂无通道'); marketCard.classList.toggle('is-ready', !!market.ready); marketCard.appendChild(el('p', 'geo-admin__muted', '上游应用编码：' + (market.upstream_app_code || 'aigc_geo') + '；按次结算，价格读取应用 API SKU。')); content.appendChild(marketCard); setStatus(Number(config.status) === 1 ? '运行中' : '已停用', Number(config.status) === 1 ? 'success' : 'warning'); } catch (error) { content.innerHTML = ''; content.appendChild(card('读取失败', error.message)); setStatus('读取失败', 'error'); } }
    function renderConfig() { content.innerHTML = ''; var node = card('品牌资料', '保存后会作为问题生成、文章生产和品牌检测的共同上下文。'); node.innerHTML += '<label>品牌名称<input id="geo-brand-name" type="text"></label><label>官网地址<input id="geo-website" type="url"></label><label>所属行业<input id="geo-industry" type="text"></label><label>企业介绍<textarea id="geo-intro" rows="5"></textarea></label><button id="geo-config-save" class="geo-admin__primary" type="button">保存配置</button>'; node.querySelector('#geo-brand-name').value = config.brand_name || ''; node.querySelector('#geo-website').value = config.website || ''; node.querySelector('#geo-industry').value = config.industry || ''; node.querySelector('#geo-intro').value = config.company_intro || ''; node.querySelector('#geo-config-save').addEventListener('click', async function () { var button = this; button.disabled = true; try { config = await api('app.aigc_geo.config/setup', { method: 'POST', body: JSON.stringify({ brand_name: node.querySelector('#geo-brand-name').value, website: node.querySelector('#geo-website').value, industry: node.querySelector('#geo-industry').value, company_intro: node.querySelector('#geo-intro').value }) }); setStatus('已保存', 'success'); } catch (error) { setStatus(error.message, 'error'); } finally { button.disabled = false; } }); content.appendChild(node); }
    async function loadTab(next) { tab = next; if (next === 'config') { if (!config.status) config = await api('app.aigc_geo.config/detail', { method: 'GET', headers: {} }); renderConfig(); return; } if (next === 'summary') return loadSummary(); var routes = { keywords: 'keyword/lists', articles: 'article/lists', diagnosis: 'diagnosis/lists', tasks: 'task/lists' }; try { var data = await api('app.aigc_geo.' + routes[next] + '?page_no=1&page_size=50', { method: 'GET', headers: {} }); content.innerHTML = ''; var node = card({ keywords: '问题关键词', articles: '内容文章', diagnosis: '品牌检测', tasks: '任务记录' }[next], '数据来自 GEO 应用业务接口。'); var list = el('div', 'geo-admin__list'); (data.lists || []).forEach(function (row) { var item = el('div', 'geo-admin__row'); item.appendChild(el('strong', '', row.question || row.title || (row.task_type + ' #' + row.id) || '-')); item.appendChild(el('span', '', row.status || row.platform || '')); list.appendChild(item); }); if (!list.children.length) list.appendChild(el('div', 'geo-admin__empty', '暂无记录')); node.appendChild(list); content.appendChild(node); setStatus('已更新', 'success'); } catch (error) { content.innerHTML = ''; content.appendChild(card('读取失败', error.message)); setStatus('读取失败', 'error'); } }
    root.querySelectorAll('[data-tab]').forEach(function (button) { button.addEventListener('click', function () { root.querySelectorAll('[data-tab]').forEach(function (item) { item.classList.toggle('is-active', item === button); }); loadTab(button.dataset.tab); }); });
    loadSummary();
  }
  function check() { if (!isPage()) { var old = document.getElementById(id); if (old) old.remove(); mounted = false; return; } if (!mounted && document.body) render(); }
  ['pushState', 'replaceState'].forEach(function (method) { var original = history[method]; history[method] = function () { var result = original.apply(this, arguments); setTimeout(check, 0); return result; }; });
  addEventListener('popstate', check); if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', check); else check();
})();
