CREATE TABLE IF NOT EXISTS `la_ai_task_operation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `operation_no` varchar(40) NOT NULL DEFAULT '',
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `admin_id` int unsigned NOT NULL DEFAULT 0,
  `terminal` varchar(20) NOT NULL DEFAULT '',
  `action` varchar(32) NOT NULL DEFAULT '',
  `reason` varchar(300) NOT NULL DEFAULT '',
  `total_count` int unsigned NOT NULL DEFAULT 0,
  `success_count` int unsigned NOT NULL DEFAULT 0,
  `failed_count` int unsigned NOT NULL DEFAULT 0,
  `skipped_count` int unsigned NOT NULL DEFAULT 0,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `summary` text,
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `finish_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_operation_no` (`operation_no`), KEY `idx_tenant_time` (`tenant_id`,`create_time`), KEY `idx_status` (`status`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI任务批量操作单';

CREATE TABLE IF NOT EXISTS `la_ai_task_operation_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `operation_id` bigint unsigned NOT NULL DEFAULT 0,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `record_key` varchar(80) NOT NULL DEFAULT '',
  `record_type` varchar(20) NOT NULL DEFAULT '',
  `app_task_id` int unsigned NOT NULL DEFAULT 0,
  `consumption_id` int unsigned NOT NULL DEFAULT 0,
  `business_table` varchar(80) NOT NULL DEFAULT '',
  `business_id` int unsigned NOT NULL DEFAULT 0,
  `upstream_task_id` varchar(255) NOT NULL DEFAULT '',
  `action` varchar(32) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `skip_reason` varchar(500) NOT NULL DEFAULT '',
  `before_status` varchar(32) NOT NULL DEFAULT '',
  `after_status` varchar(32) NOT NULL DEFAULT '',
  `before_billing_status` varchar(32) NOT NULL DEFAULT '',
  `after_billing_status` varchar(32) NOT NULL DEFAULT '',
  `before_snapshot` text,
  `after_snapshot` text,
  `result_message` varchar(1000) NOT NULL DEFAULT '',
  `job_key` varchar(120) NOT NULL DEFAULT '',
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `finish_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_job_key` (`job_key`), KEY `idx_operation` (`operation_id`,`id`), KEY `idx_task` (`app_task_id`,`consumption_id`), KEY `idx_tenant_status` (`tenant_id`,`status`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI任务批量操作明细';

CREATE TABLE IF NOT EXISTS `la_ai_task_delete_receipt` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `operation_id` bigint unsigned NOT NULL DEFAULT 0,
  `operation_item_id` bigint unsigned NOT NULL DEFAULT 0,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `admin_id` int unsigned NOT NULL DEFAULT 0,
  `record_key` varchar(80) NOT NULL DEFAULT '',
  `target_summary` text,
  `delete_summary` text,
  `create_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), KEY `idx_operation_item` (`operation_item_id`), KEY `idx_tenant_time` (`tenant_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI任务物理删除回执';
