<template>
    <view class="page">
        <view class="topbar" :style="topbarStyle"><view class="nav-row" :style="navRowStyle"><view class="nav-button" @click="goBack"><u-icon name="arrow-left" color="#111" size="38" /></view><view class="topbar-title" :style="titleStyle">我的声音</view><view class="nav-placeholder" :style="navPlaceholderStyle" /></view></view>
        <scroll-view class="content" scroll-y>
            <view v-for="voice in voices" :key="voice.id" class="voice-item" @click="selectVoice(voice)"><view class="voice-play">▶</view><view class="voice-info"><text>{{ voice.name }}</text><text>{{ voice.createdAt || '本地声音' }}</text></view><text class="more" @click.stop="showActions(voice)">•••</text></view>
            <view v-if="!voices.length" class="empty"><view class="empty-plus" @click="openCreate">＋</view><text class="empty-title">还没有声音</text><text>选择录音、上传文件或输入音频链接</text><button @click="openCreate">新建声音</button></view>
            <view v-else class="voice-create" @click="openCreate"><view class="plus">＋</view><text>新建声音</text></view><view v-if="voices.length" class="more-tip">— 没有更多了 —</view>
        </scroll-view>
        <view v-if="createVisible" class="mask" @click="createVisible = false"><view class="sheet" @click.stop><view class="sheet-title">新建声音</view><view @click="startRecord">录制声音</view><view @click="chooseFile">上传音频文件</view><view @click="showLinkInput">输入音频链接</view><view class="cancel" @click="createVisible = false">取消</view></view></view>
        <view v-if="linkVisible" class="mask" @click="linkVisible = false"><view class="link-sheet" @click.stop><text class="sheet-title">输入声音链接</text><input v-model="linkUrl" placeholder="https://.../voice.mp3" /><input v-model="linkName" placeholder="声音名称（可选）" /><button @click="saveLink">保存声音</button></view></view>
        <view v-if="recording" class="record-mask"><view class="record-card"><text class="record-title">正在录音</text><text class="record-time">{{ recordSeconds }}s</text><button @click="stopRecord">完成录音</button><text @click="cancelRecord">取消</text></view></view>
        <view v-if="actionVoice" class="mask" @click="actionVoice = null"><view class="sheet" @click.stop><view @click="renameVoice">修改名称</view><view class="danger" @click="deleteVoice">删除</view><view class="cancel" @click="actionVoice = null">取消</view></view></view>
    </view>
</template>
<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
type Voice = { id: string; name: string; path: string; url?: string; createdAt: string }
const voices = ref<Voice[]>([]); const createVisible = ref(false); const linkVisible = ref(false); const linkUrl = ref(''); const linkName = ref(''); const actionVoice = ref<Voice | null>(null); const recording = ref(false); const recordSeconds = ref(0); let recordTimer: ReturnType<typeof setInterval> | undefined; let recorder: any
const navMetrics = reactive({ menuTop: 44, menuHeight: 32, menuWidth: 88, navHeight: 88 }); const load = () => { try { voices.value = uni.getStorageSync('music_cover_voices') || [] } catch { voices.value = [] } }; const save = () => uni.setStorageSync('music_cover_voices', voices.value)
const addVoice = (voice: Voice) => { voices.value.unshift(voice); save(); uni.$emit('music-cover-voice-selected', voice); uni.navigateBack({ delta: 1 }) }
const openCreate = () => { createVisible.value = true }; const chooseFile = () => { createVisible.value = false; /* #ifdef MP-WEIXIN */ uni.chooseMessageFile({ count: 1, type: 'file', extension: ['mp3', 'wav', 'm4a', 'aac', 'ogg', 'flac'] }).then((res: any) => { const f = res?.tempFiles?.[0]; if (f?.path) addVoice({ id: `${Date.now()}`, name: f.name || '我的声音', path: f.path, createdAt: '刚刚创建' }) }).catch(() => uni.$u.toast('未选择声音文件')) /* #endif */ /* #ifdef H5 */ (uni as any).chooseFile({ count: 1, type: 'audio' }).then((res: any) => { const f = res?.tempFiles?.[0]; if (f?.path) addVoice({ id: `${Date.now()}`, name: f.name || '我的声音', path: f.path, createdAt: '刚刚创建' }) }).catch(() => uni.$u.toast('未选择声音文件')) /* #endif */ }
const showLinkInput = () => { createVisible.value = false; linkVisible.value = true }; const saveLink = () => { const url = linkUrl.value.trim(); if (!/^https?:\/\//i.test(url)) return uni.$u.toast('请输入有效的音频链接'); addVoice({ id: `${Date.now()}`, name: linkName.value.trim() || '链接声音', path: '', url, createdAt: '刚刚创建' }); linkVisible.value = false; linkUrl.value = ''; linkName.value = '' }
const startRecord = () => { createVisible.value = false; recording.value = true; recordSeconds.value = 0; recordTimer = setInterval(() => recordSeconds.value += 1, 1000); /* #ifdef MP-WEIXIN */ recorder = uni.getRecorderManager(); recorder.onStop((res: any) => finishRecord(res.tempFilePath)); recorder.start({ duration: 60000, sampleRate: 44100, numberOfChannels: 1, encodeBitRate: 192000, format: 'mp3' }) /* #endif */ /* #ifdef H5 */ if (typeof navigator !== 'undefined' && navigator.mediaDevices?.getUserMedia) navigator.mediaDevices.getUserMedia({ audio: true }).then((stream: any) => { const chunks: Blob[] = []; const mr = new MediaRecorder(stream); mr.ondataavailable = (e: any) => chunks.push(e.data); (recorder as any) = { stop: () => { mr.stop(); stream.getTracks().forEach((t: any) => t.stop()) } }; mr.onstop = () => finishRecord(URL.createObjectURL(new Blob(chunks, { type: 'audio/webm' }))); mr.start() }).catch(() => { recording.value = false; uni.$u.toast('无法访问麦克风') }) /* #endif */ }
const finishRecord = (path: string) => { recording.value = false; if (recordTimer) clearInterval(recordTimer); addVoice({ id: `${Date.now()}`, name: `录音声音 ${new Date().toLocaleTimeString()}`, path, createdAt: '刚刚创建' }) }; const stopRecord = () => { recorder?.stop?.() }; const cancelRecord = () => { recorder?.stop?.(); recording.value = false; if (recordTimer) clearInterval(recordTimer) }
const selectVoice = (voice: Voice) => { uni.$emit('music-cover-voice-selected', voice); uni.navigateBack({ delta: 1 }) }; const showActions = (voice: Voice) => { actionVoice.value = voice }; const renameVoice = () => { if (!actionVoice.value) return; uni.showModal({ title: '修改名称', editable: true, placeholderText: actionVoice.value.name, success: r => { if (r.confirm && r.content) { actionVoice.value!.name = r.content; save() }; actionVoice.value = null } }) }; const deleteVoice = () => { if (!actionVoice.value) return; voices.value = voices.value.filter(v => v.id !== actionVoice.value!.id); save(); actionVoice.value = null }; const goBack = () => uni.navigateBack({ delta: 1 })
const topbarStyle = computed(() => ({ height: `${navMetrics.navHeight}px` })); const navRowStyle = computed(() => ({ top: `${navMetrics.menuTop}px`, height: `${navMetrics.menuHeight}px`, right: `${navMetrics.menuWidth + 24}px` })); const titleStyle = computed(() => ({ top: `${navMetrics.menuTop}px`, height: `${navMetrics.menuHeight}px`, lineHeight: `${navMetrics.menuHeight}px`, left: '0', right: '0' })); const navPlaceholderStyle = computed(() => ({ width: '136rpx', height: `${navMetrics.menuHeight}px` })); const init = () => { const i = uni.getSystemInfoSync(); /* #ifdef MP-WEIXIN */ const m = uni.getMenuButtonBoundingClientRect(); navMetrics.menuTop = m.top; navMetrics.menuHeight = m.height; navMetrics.menuWidth = i.windowWidth - m.left; navMetrics.navHeight = m.top + m.height + 10; /* #endif */ }; init(); onMounted(load); onUnmounted(() => { if (recordTimer) clearInterval(recordTimer) })
</script>
<style scoped lang="scss">.page{min-height:100vh;background:#fff;color:#111}.topbar{position:fixed;left:0;right:0;top:0;z-index:10;background:#fff}.nav-row{position:absolute;left:28rpx;display:flex;align-items:center;justify-content:space-between}.nav-button{width:72rpx;height:100%;display:flex;align-items:center}.topbar-title{position:fixed;z-index:1;text-align:center;font-size:32rpx;font-weight:700;pointer-events:none}.content{height:100vh;box-sizing:border-box;padding:calc(28rpx + var(--status-bar-height)) 32rpx 60rpx}.voice-item,.voice-create{display:flex;align-items:center;gap:28rpx;padding:20rpx 0}.voice-create{font-size:34rpx;font-weight:700}.plus,.voice-play{width:96rpx;height:96rpx;border-radius:20rpx;background:#f8f9fb;display:flex;align-items:center;justify-content:center}.plus{font-size:56rpx}.voice-play{font-size:30rpx}.voice-info{flex:1;display:flex;flex-direction:column;gap:8rpx}.voice-info text:first-child{font-size:30rpx;font-weight:600}.voice-info text:last-child{font-size:23rpx;color:#999}.more{color:#aaa;font-size:28rpx;padding:20rpx}.empty{display:flex;flex-direction:column;align-items:center;gap:12rpx;color:#aaa;padding:180rpx 0 40rpx;font-size:25rpx}.empty-plus{width:112rpx;height:112rpx;border-radius:50%;background:#f8f9fb;color:#111;display:flex;align-items:center;justify-content:center;font-size:58rpx}.empty-title{color:#111;font-size:32rpx;font-weight:700}.empty button,.link-sheet button{margin-top:18rpx;border:0;border-radius:40rpx;background:#c7ff00;color:#111;padding:0 48rpx;font-size:28rpx}.more-tip{text-align:center;color:#aaa;padding:70rpx 0;font-size:26rpx}.mask,.record-mask{position:fixed;inset:0;z-index:20;background:rgba(0,0,0,.32);display:flex;align-items:flex-end}.sheet,.link-sheet,.record-card{width:100%;background:#fff;text-align:center;font-size:32rpx}.sheet view{padding:30rpx;border-bottom:1rpx solid #f2f2f2}.sheet-title{font-size:34rpx;font-weight:700;padding:30rpx}.sheet .danger{color:#f44}.sheet .cancel{margin-top:12rpx;border:0}.link-sheet{padding:34rpx;box-sizing:border-box}.link-sheet input{height:80rpx;margin:12rpx 0;padding:0 24rpx;border-radius:16rpx;background:#f5f6f8;text-align:left;font-size:26rpx}.record-mask{align-items:center;justify-content:center}.record-card{width:520rpx;padding:48rpx 30rpx;border-radius:24rpx}.record-title{display:block;font-weight:700}.record-time{display:block;padding:30rpx;font-size:58rpx}.record-card button{background:#c7ff00;border:0;border-radius:42rpx}.record-card>text:last-child{display:block;padding-top:28rpx;color:#999;font-size:25rpx}</style>
