CREATE TABLE IF NOT EXISTS `la_aigc_canvas_delivery_plan` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `user_id` int unsigned NOT NULL DEFAULT 0,
  `project_id` int unsigned NOT NULL DEFAULT 0,
  `thread_id` int unsigned NOT NULL DEFAULT 0,
  `source_message_id` int unsigned NOT NULL DEFAULT 0,
  `title` varchar(160) NOT NULL DEFAULT '',
  `intent` varchar(80) NOT NULL DEFAULT '',
  `status` varchar(40) NOT NULL DEFAULT 'draft',
  `item_count` int unsigned NOT NULL DEFAULT 0,
  `meta_json` longtext,
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_delivery_plan_thread` (`tenant_id`,`user_id`,`thread_id`,`status`,`delete_time`),
  KEY `idx_delivery_plan_project` (`tenant_id`,`project_id`,`delete_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC canvas delivery plans';

CREATE TABLE IF NOT EXISTS `la_aigc_canvas_delivery_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL DEFAULT 0,
  `user_id` int unsigned NOT NULL DEFAULT 0,
  `project_id` int unsigned NOT NULL DEFAULT 0,
  `thread_id` int unsigned NOT NULL DEFAULT 0,
  `plan_id` int unsigned NOT NULL DEFAULT 0,
  `parent_item_id` int unsigned NOT NULL DEFAULT 0,
  `source_message_id` int unsigned NOT NULL DEFAULT 0,
  `item_key` varchar(96) NOT NULL DEFAULT '',
  `objective` text,
  `skill_key` varchar(120) NOT NULL DEFAULT '',
  `tool_code` varchar(80) NOT NULL DEFAULT '',
  `status` varchar(40) NOT NULL DEFAULT 'draft',
  `sort_order` int unsigned NOT NULL DEFAULT 0,
  `retry_count` int unsigned NOT NULL DEFAULT 0,
  `depends_on_json` longtext,
  `required_slots_json` longtext,
  `soft_slots_json` longtext,
  `slots_json` longtext,
  `delivery_json` longtext,
  `creative_context_json` longtext,
  `reference_assets_json` longtext,
  `pending_action_json` longtext,
  `skill_snapshot_json` longtext,
  `task_snapshot_json` longtext,
  `cost_json` longtext,
  `result_json` longtext,
  `provider_request_id` varchar(160) NOT NULL DEFAULT '',
  `provider_error_code` varchar(120) NOT NULL DEFAULT '',
  `provider_error_message` text,
  `error` text,
  `meta_json` longtext,
  `create_time` int unsigned NOT NULL DEFAULT 0,
  `update_time` int unsigned NOT NULL DEFAULT 0,
  `delete_time` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_item_key` (`plan_id`,`item_key`,`delete_time`),
  KEY `idx_delivery_item_thread` (`tenant_id`,`user_id`,`thread_id`,`status`,`delete_time`),
  KEY `idx_delivery_item_plan` (`plan_id`,`sort_order`,`delete_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AIGC canvas delivery items';
