<?php
declare(strict_types=1);

require __DIR__ . '/bootstrap.php';

use app\common\service\app\aigc_short_drama\ShortDramaCanvasService as Canvas;
use app\common\service\power\MarketVideoRuntimeService as Market;
use think\facade\Db;

/**
 * A provider-free boundary fixture. Quote uses the real market quote service;
 * generation only records that the Canvas intent reached its downstream seam.
 */
class P3QuoteConfirmationVideo
{
    public static int $sku = 0;
    public static int $calls = 0;
    public static function estimate(int $tenant, array $payload): array
    {
        return Market::quote($tenant, ['market_sku_id' => self::$sku] + $payload);
    }
    public static function generate(int $tenant, int $user, array $payload): array
    {
        self::$calls++;
        return ['id' => 0, 'status' => 'success', 'results' => []];
    }
}
class_alias(P3QuoteConfirmationVideo::class, 'app\\common\\service\\app\\aigc_video\\AigcVideoService');

Db::startTrans();
try {
    Db::name('tenant')->insert(['id' => 91001, 'sn' => 'p3-quote-confirm', 'create_time' => time(), 'point_balance' => 100]);
    Db::name('user')->insert(['id' => 92001, 'sn' => 92001, 'account' => 'p3-quote-confirm', 'tenant_id' => 91001, 'user_money' => 100]);
    $product = Db::name('power_market_product')->insertGetId([
        'product_code' => 'isolated-p3-quote-confirm', 'resource_type' => 'model', 'model_type' => 'video',
        'name' => 'Isolated quote confirmation video', 'source_code' => 'isolated-agent-test',
        'upstream_resource_key' => 'isolated-p3-quote-confirm', 'upstream_model_code' => 'isolated-p3-quote-confirm',
        'upstream_channel_code' => 'isolated-channel', 'status' => 1,
    ]);
    P3QuoteConfirmationVideo::$sku = Db::name('power_market_sku')->insertGetId([
        'product_id' => $product, 'sku_key' => 'video-call', 'title' => 'Isolated video call',
        'usage_unit' => 'call', 'sale_points' => 2, 'status' => 1, 'sale_status' => 1, 'locked_params' => '{"duration":5}',
    ]);
    $canvas = Canvas::create(91001, 92001, ['title' => 'P3 quote confirmation'])['id'];
    Canvas::save(91001, 92001, ['id' => $canvas, 'nodes' => [['id' => 1, 'type' => 'video', 'metadata' => ['content_revision' => 1]]]]);
    $request = [
        'canvas_id' => $canvas, 'node_id' => '1', 'type' => 'video', 'prompt' => 'Synthetic quoted video',
        'request_key' => 'quoted-video', 'model_id' => 'market_video_model:' . $product, 'resolution' => '720p', 'duration' => 5,
    ];
    $before = [Db::name('ai_app_task')->count(), Db::name('ai_consumption_log')->count()];
    $quote = Canvas::quote(91001, 92001, $request);
    agentCheck($quote['status'] === 'quoted' && $quote['quote']['market_sku_id'] === P3QuoteConfirmationVideo::$sku, 'M14 quote is generated by real market validation without a task');
    agentCheck($before === [Db::name('ai_app_task')->count(), Db::name('ai_consumption_log')->count()] && P3QuoteConfirmationVideo::$calls === 0, 'M14 quote does not reserve or call Provider');
    $confirmed = Canvas::confirmQuote(91001, 92001, ['canvas_id' => $canvas, 'node_id' => '1', 'quote_token' => $quote['quote_token']]);
    agentCheck($confirmed['status'] === 'confirmed' && $confirmed['quote_token'] === $quote['quote_token'], 'M14 explicit user confirmation is durable and replay-safe');

    foreach (['model_id' => 'market_video_model:changed', 'resolution' => '1080p', 'duration' => 8] as $field => $value) {
        $changed = $request;
        $changed[$field] = $value;
        $changed['quote_token'] = $quote['quote_token'];
        $blocked = false;
        try { Canvas::submitIdempotent(91001, 92001, $changed); } catch (Throwable $error) { $blocked = $error->getMessage() === 'QUOTE_INPUT_CHANGED'; }
        agentCheck($blocked && P3QuoteConfirmationVideo::$calls === 0, 'M14 changed ' . $field . ' invalidates confirmation before Provider submission');
    }

    $request['quote_token'] = $confirmed['quote_token'];
    $run = Canvas::submitIdempotent(91001, 92001, $request);
    agentCheck($run['status'] === 'running' && P3QuoteConfirmationVideo::$calls === 1, 'M14 matching confirmed quote reaches one idempotent generation intent');
    $replay = Canvas::submitIdempotent(91001, 92001, array_diff_key($request, ['quote_token' => true]));
    agentCheck($replay['id'] === $run['id'] && P3QuoteConfirmationVideo::$calls === 1, 'M14 accepted run replay does not require a fresh quote or resubmit');

    $next = array_replace($request, ['request_key' => 'quoted-after-plan-change']);
    $nextQuote = Canvas::quote(91001, 92001, array_diff_key($next, ['quote_token' => true]));
    Canvas::confirmQuote(91001, 92001, ['canvas_id' => $canvas, 'node_id' => '1', 'quote_token' => $nextQuote['quote_token']]);
    $current = Canvas::current(91001, 92001, $canvas);
    // A real target-node edit must invalidate a quote.  A bare document save
    // is intentionally not part of the commercial hash: runtime progress and
    // unrelated layout changes can advance graph_revision while the user is
    // reading the confirmation dialog.
    $changedNodes = $current['nodes'];
    $changedNodes[0]['metadata']['prompt'] = 'Edited after quote';
    Canvas::save(91001, 92001, ['id' => $canvas, 'nodes' => $changedNodes, 'edges' => $current['edges'], 'expected_revision' => $current['graph_revision']]);
    $next['quote_token'] = $nextQuote['quote_token'];
    $blocked = false;
    try { Canvas::submitIdempotent(91001, 92001, $next); } catch (Throwable $error) { $blocked = $error->getMessage() === 'QUOTE_INPUT_CHANGED'; }
    agentCheck($blocked && P3QuoteConfirmationVideo::$calls === 1, 'M14 priced target-node edit invalidates a previously confirmed quote');
} finally {
    Db::rollback();
}

echo "NOT_RUN HTTP/UI confirmation click and real Provider/media task; isolated real market quote and Canvas hash gate tested\n";
